package view;

import dao.FuncionarioDAO;
import javax.swing.JOptionPane;
import model.CadastroFuncionario;

/**
 *
 * @author ANNY FIORESE
 */
public class Cadastro extends javax.swing.JFrame {
    
    FuncionarioDAO funcionarioDAO = new FuncionarioDAO();

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EstadoCadastro = new javax.swing.JTextField();
        UsuarioCadastro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        BairroCadastro = new javax.swing.JTextField();
        RuaCadastro = new javax.swing.JTextField();
        NomeCadastro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CidadeCadastro = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        SenhaCadastro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        NumCadastro = new javax.swing.JFormattedTextField();
        TelefoneCadastro = new javax.swing.JFormattedTextField();
        CpfCadastro = new javax.swing.JFormattedTextField();
        NascimentoCadastro = new javax.swing.JFormattedTextField();
        VoltarCadastro = new javax.swing.JToggleButton();
        ConfirmarCadastro = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(EstadoCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, 130, -1));
        getContentPane().add(UsuarioCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 130, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Bairro");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 60, 20));

        BairroCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BairroCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(BairroCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 130, -1));

        RuaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RuaCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(RuaCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 330, -1));

        NomeCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(NomeCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 400, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Estado");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 60, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Usuario");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 60, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Telefone");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 60, 20));
        getContentPane().add(CidadeCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 120, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Senha");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 60, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nº");
        jLabel13.setToolTipText("");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 60, 20));

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cidade");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 60, -1));
        getContentPane().add(SenhaCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 120, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Rua");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 60, 20));

        NumCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("######"))));
        getContentPane().add(NumCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 60, -1));

        try {
            TelefoneCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TelefoneCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefoneCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(TelefoneCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 130, -1));

        try {
            CpfCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(CpfCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 120, -1));

        try {
            NascimentoCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        NascimentoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NascimentoCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(NascimentoCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 130, -1));

        VoltarCadastro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        VoltarCadastro.setBorder(null);
        VoltarCadastro.setContentAreaFilled(false);
        VoltarCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VoltarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(VoltarCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        ConfirmarCadastro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ConfirmarCadastro.setText("Confirmar");
        ConfirmarCadastro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ConfirmarCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ConfirmarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(ConfirmarCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 400, 20));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nome");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 60, 20));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CPF");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 60, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data de nascimento");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 130, 20));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cadastro");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 160, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Cadastro.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 820, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BairroCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BairroCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BairroCadastroActionPerformed

    private void RuaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RuaCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RuaCadastroActionPerformed

    private void VoltarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarCadastroActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VoltarCadastroActionPerformed

    private void ConfirmarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarCadastroActionPerformed
        // TODO add your handling code here:
        CadastroFuncionario cadastro = new CadastroFuncionario();
        cadastro.setUsuario(UsuarioCadastro.getText().toString());
        cadastro.setSenha(SenhaCadastro.getText().toString());
        cadastro.setNome(NomeCadastro.getText().toString());
        cadastro.setNascimento(NascimentoCadastro.getText().toString());
        cadastro.setCpf(CpfCadastro.getText().toString());
        cadastro.setRua(RuaCadastro.getText().toString());
        cadastro.setNumero(Integer.parseInt(NumCadastro.getText().toString()));
        cadastro.setBairro(BairroCadastro.getText().toString());
        cadastro.setCidade(CidadeCadastro.getText().toString());
        cadastro.setEstado(EstadoCadastro.getText().toString());
        
        funcionarioDAO.inserir(cadastro);
        
        JOptionPane.showMessageDialog(null, "O Usuario " + UsuarioCadastro.getText().trim() + " foi cadastrado !!");
        
    }//GEN-LAST:event_ConfirmarCadastroActionPerformed

    private void NascimentoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NascimentoCadastroActionPerformed

    }//GEN-LAST:event_NascimentoCadastroActionPerformed

    private void TelefoneCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefoneCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefoneCadastroActionPerformed

    private void NomeCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BairroCadastro;
    private javax.swing.JTextField CidadeCadastro;
    private javax.swing.JToggleButton ConfirmarCadastro;
    private javax.swing.JFormattedTextField CpfCadastro;
    private javax.swing.JTextField EstadoCadastro;
    private javax.swing.JFormattedTextField NascimentoCadastro;
    private javax.swing.JTextField NomeCadastro;
    private javax.swing.JFormattedTextField NumCadastro;
    private javax.swing.JTextField RuaCadastro;
    private javax.swing.JTextField SenhaCadastro;
    private javax.swing.JFormattedTextField TelefoneCadastro;
    private javax.swing.JTextField UsuarioCadastro;
    private javax.swing.JToggleButton VoltarCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
