package view;

import dao.DispesasDAO;
import javax.swing.JOptionPane;
import model.Dispesas;

/**
 *
 * @author ANNY FIORESE
 */
public class Despesas extends javax.swing.JFrame {

    DispesasDAO dispesasDAO = new DispesasDAO();

    /**
     * Creates new form Despesas
     */
    public Despesas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DataGastos = new javax.swing.JFormattedTextField();
        ValorGastos = new javax.swing.JFormattedTextField();
        TipoGasto = new javax.swing.JComboBox<>();
        DescriDespesa = new javax.swing.JScrollPane();
        DescriçãoGasto = new javax.swing.JTextArea();
        ConfirmarGasto = new javax.swing.JButton();
        VoltarGasto = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        try {
            DataGastos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        DataGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataGastosActionPerformed(evt);
            }
        });
        getContentPane().add(DataGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 310, -1));

        ValorGastos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        ValorGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorGastosActionPerformed(evt);
            }
        });
        getContentPane().add(ValorGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 310, -1));

        TipoGasto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pagamento Funcionario", "Item para Instituição", "Eventos", "Manutençao", "Luz", "Água ", "Aluguel", "Doação", "Outros", " " }));
        TipoGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoGastoActionPerformed(evt);
            }
        });
        getContentPane().add(TipoGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 310, -1));

        DescriçãoGasto.setColumns(20);
        DescriçãoGasto.setRows(5);
        DescriDespesa.setViewportView(DescriçãoGasto);

        getContentPane().add(DescriDespesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 310, -1));

        ConfirmarGasto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ConfirmarGasto.setText("Confimar");
        ConfirmarGasto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ConfirmarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarGastoActionPerformed(evt);
            }
        });
        getContentPane().add(ConfirmarGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, 310, 20));

        VoltarGasto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        VoltarGasto.setBorder(null);
        VoltarGasto.setContentAreaFilled(false);
        VoltarGasto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VoltarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarGastoActionPerformed(evt);
            }
        });
        getContentPane().add(VoltarGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Descrição");
        jLabel11.setToolTipText("");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, -1, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Gastos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Valor");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 90, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tipo");
        jLabel10.setToolTipText("");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Data");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Gastos.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarGastoActionPerformed
        Dispesas dispesa = new Dispesas();
        dispesa.setData(DataGastos.getText().toString());
        dispesa.setValor(ValorGastos.getText().toString());
        dispesa.setTipoDePagamento(TipoGasto.getSelectedItem().toString());
        dispesa.setDescricao(DescriçãoGasto.getText().toString());
        try {
             dispesasDAO.inserir(dispesa);
             JOptionPane.showMessageDialog(null, " Saida lançada com sucesso !!");
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, " Erro ao realizar o lançamento tente novamente !!");
        }
       

    }//GEN-LAST:event_ConfirmarGastoActionPerformed

    private void DataGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataGastosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataGastosActionPerformed

    private void VoltarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarGastoActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VoltarGastoActionPerformed

    private void ValorGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorGastosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorGastosActionPerformed

    private void TipoGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoGastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoGastoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Despesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Despesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Despesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Despesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Despesas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmarGasto;
    private javax.swing.JFormattedTextField DataGastos;
    private javax.swing.JScrollPane DescriDespesa;
    private javax.swing.JTextArea DescriçãoGasto;
    private javax.swing.JComboBox<String> TipoGasto;
    private javax.swing.JFormattedTextField ValorGastos;
    private javax.swing.JButton VoltarGasto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
