/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.DizimistaDAO;
import javax.swing.JOptionPane;
import model.CadastroDizimista;

/**
 *
 * @author ANNY FIORESE
 */
public class Dizimista extends javax.swing.JFrame {

    DizimistaDAO dizimistaDAO = new DizimistaDAO();

    /**
     * Creates new form Dizimista
     */
    public Dizimista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NascimentoFiel = new javax.swing.JFormattedTextField();
        NumFiel = new javax.swing.JFormattedTextField();
        RuaFiel = new javax.swing.JTextField();
        CidadeFiel = new javax.swing.JTextField();
        BairroFiel = new javax.swing.JTextField();
        EstadoFiel = new javax.swing.JTextField();
        CpfFiel = new javax.swing.JFormattedTextField();
        TelefoneFiel = new javax.swing.JFormattedTextField();
        NomeFiel = new javax.swing.JTextField();
        Voltarfiel = new javax.swing.JButton();
        ConfirmarFiel = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        aa = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        try {
            NascimentoFiel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        NascimentoFiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NascimentoFielActionPerformed(evt);
            }
        });
        getContentPane().add(NascimentoFiel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 150, 20));

        NumFiel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        getContentPane().add(NumFiel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, 60, 20));

        RuaFiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RuaFielActionPerformed(evt);
            }
        });
        getContentPane().add(RuaFiel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 320, 20));
        getContentPane().add(CidadeFiel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 110, 20));

        BairroFiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BairroFielActionPerformed(evt);
            }
        });
        getContentPane().add(BairroFiel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 150, 20));
        getContentPane().add(EstadoFiel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 100, 20));

        try {
            CpfFiel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(CpfFiel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 130, 20));

        try {
            TelefoneFiel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(TelefoneFiel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 190, -1));
        getContentPane().add(NomeFiel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 400, 20));

        Voltarfiel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Voltarfiel.setBorder(null);
        Voltarfiel.setContentAreaFilled(false);
        Voltarfiel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Voltarfiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarfielActionPerformed(evt);
            }
        });
        getContentPane().add(Voltarfiel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 40, 40));

        ConfirmarFiel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ConfirmarFiel.setText("Confirmar");
        ConfirmarFiel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ConfirmarFiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarFielActionPerformed(evt);
            }
        });
        getContentPane().add(ConfirmarFiel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 400, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CPF");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Cidade");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, -1, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Estado");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, -1, 20));

        aa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        aa.setForeground(new java.awt.Color(255, 255, 255));
        aa.setText("Data de Nascimento");
        getContentPane().add(aa, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, -1, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Rua");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, -1, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nº");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, 20, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Bairro");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, -1, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nome");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, 20));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Telefone");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cadastro de Fiel");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Dizimista.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 820, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarfielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarfielActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VoltarfielActionPerformed

    private void BairroFielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BairroFielActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BairroFielActionPerformed

    private void NascimentoFielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NascimentoFielActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NascimentoFielActionPerformed

    private void RuaFielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RuaFielActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RuaFielActionPerformed

    private void ConfirmarFielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarFielActionPerformed
        // TODO add your handling code here:
        CadastroDizimista dizimista = new CadastroDizimista();
        // int codigo, String nome, String nascimento, float cpf, String rua,int numero, String bairro, String cidade, String estado
        dizimista.setNome(NomeFiel.getText().toString());
        dizimista.setNascimento(NascimentoFiel.getText().toString());
        dizimista.setCpf(CpfFiel.getText().toString());
        dizimista.setRua(RuaFiel.getText().toString());
        dizimista.setNumero(Long.parseLong(NumFiel.getText().toString()));
        dizimista.setBairro(BairroFiel.getText().toString());
        dizimista.setCidade(CidadeFiel.getText().toString());
        dizimista.setEstado(EstadoFiel.getText().toString());
        dizimistaDAO.inserir(dizimista);

        JOptionPane.showMessageDialog(null, " Novo fiel cadastrado!!");


    }//GEN-LAST:event_ConfirmarFielActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dizimista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dizimista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dizimista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dizimista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dizimista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BairroFiel;
    private javax.swing.JTextField CidadeFiel;
    private javax.swing.JButton ConfirmarFiel;
    private javax.swing.JFormattedTextField CpfFiel;
    private javax.swing.JTextField EstadoFiel;
    private javax.swing.JFormattedTextField NascimentoFiel;
    private javax.swing.JTextField NomeFiel;
    private javax.swing.JFormattedTextField NumFiel;
    private javax.swing.JTextField RuaFiel;
    private javax.swing.JFormattedTextField TelefoneFiel;
    private javax.swing.JButton Voltarfiel;
    private javax.swing.JLabel aa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
