package view;

/**
 *
 * @author ANNY FIORESE
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DispesasMenu = new javax.swing.JToggleButton();
        RecebimentoMenu = new javax.swing.JToggleButton();
        RelatorioMenu = new javax.swing.JToggleButton();
        CadastroMenu = new javax.swing.JToggleButton();
        VoltarMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DispesasMenu.setBackground(new java.awt.Color(0, 0, 0));
        DispesasMenu.setForeground(new java.awt.Color(255, 255, 255));
        DispesasMenu.setToolTipText("");
        DispesasMenu.setBorder(null);
        DispesasMenu.setBorderPainted(false);
        DispesasMenu.setContentAreaFilled(false);
        DispesasMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DispesasMenu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DispesasMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DispesasMenuActionPerformed(evt);
            }
        });
        getContentPane().add(DispesasMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 100, 130));

        RecebimentoMenu.setBackground(new java.awt.Color(0, 0, 0));
        RecebimentoMenu.setForeground(new java.awt.Color(255, 255, 255));
        RecebimentoMenu.setToolTipText("");
        RecebimentoMenu.setBorder(null);
        RecebimentoMenu.setBorderPainted(false);
        RecebimentoMenu.setContentAreaFilled(false);
        RecebimentoMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RecebimentoMenu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RecebimentoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecebimentoMenuActionPerformed(evt);
            }
        });
        getContentPane().add(RecebimentoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 110, 140));

        RelatorioMenu.setBackground(new java.awt.Color(0, 0, 0));
        RelatorioMenu.setForeground(new java.awt.Color(255, 255, 255));
        RelatorioMenu.setToolTipText("");
        RelatorioMenu.setBorder(null);
        RelatorioMenu.setBorderPainted(false);
        RelatorioMenu.setContentAreaFilled(false);
        RelatorioMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RelatorioMenu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RelatorioMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatorioMenuActionPerformed(evt);
            }
        });
        getContentPane().add(RelatorioMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 120, 130));

        CadastroMenu.setBackground(new java.awt.Color(0, 0, 0));
        CadastroMenu.setForeground(new java.awt.Color(255, 255, 255));
        CadastroMenu.setToolTipText("");
        CadastroMenu.setBorder(null);
        CadastroMenu.setBorderPainted(false);
        CadastroMenu.setContentAreaFilled(false);
        CadastroMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CadastroMenu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CadastroMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroMenuActionPerformed(evt);
            }
        });
        getContentPane().add(CadastroMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 130, 130));

        VoltarMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        VoltarMenu.setBorder(null);
        VoltarMenu.setContentAreaFilled(false);
        VoltarMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VoltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarMenuActionPerformed(evt);
            }
        });
        getContentPane().add(VoltarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Menu_1.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastroMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroMenuActionPerformed
        // TODO add your handling code here:
        Dizimista dizimista = new Dizimista();
        dizimista.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CadastroMenuActionPerformed

    private void RelatorioMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatorioMenuActionPerformed
        // TODO add your handling code here:
        Relatorio relatorio = new Relatorio();
        relatorio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RelatorioMenuActionPerformed

    private void RecebimentoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecebimentoMenuActionPerformed
        // TODO add your handling code here:
        Recebimentos recibemento = new Recebimentos();
        recibemento.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RecebimentoMenuActionPerformed

    private void DispesasMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DispesasMenuActionPerformed
        // TODO add your handling code here:
        Despesas despesa = new Despesas();
        despesa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DispesasMenuActionPerformed

    private void VoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarMenuActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VoltarMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton CadastroMenu;
    private javax.swing.JToggleButton DispesasMenu;
    private javax.swing.JToggleButton RecebimentoMenu;
    private javax.swing.JToggleButton RelatorioMenu;
    private javax.swing.JButton VoltarMenu;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
