/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.RecebimentoDAO;
import javax.swing.JOptionPane;
import model.Recebimento;

/**
 *
 * @author ANNY FIORESE
 */
public class Recebimentos extends javax.swing.JFrame {

    RecebimentoDAO recebimentoDAO = new RecebimentoDAO();

    /**
     * Creates new form Pesquisar
     */
    public Recebimentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoReceb = new javax.swing.JComboBox<>();
        NomeRecebi = new javax.swing.JTextField();
        DataRecebi = new javax.swing.JFormattedTextField();
        ValorRecebi = new javax.swing.JFormattedTextField();
        VoltarRecebi = new javax.swing.JButton();
        confirmarRecebi = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TipoReceb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dizimo", "Ofertas", "Doação", "Outros" }));
        getContentPane().add(TipoReceb, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 302, 190, -1));

        NomeRecebi.setToolTipText("");
        getContentPane().add(NomeRecebi, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 400, -1));

        try {
            DataRecebi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        DataRecebi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataRecebiActionPerformed(evt);
            }
        });
        getContentPane().add(DataRecebi, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 190, -1));

        ValorRecebi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        ValorRecebi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorRecebiActionPerformed(evt);
            }
        });
        getContentPane().add(ValorRecebi, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 190, -1));

        VoltarRecebi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        VoltarRecebi.setBorder(null);
        VoltarRecebi.setContentAreaFilled(false);
        VoltarRecebi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VoltarRecebi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarRecebiActionPerformed(evt);
            }
        });
        getContentPane().add(VoltarRecebi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 40, 40));

        confirmarRecebi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        confirmarRecebi.setText("Confirmar");
        confirmarRecebi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        confirmarRecebi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarRecebiActionPerformed(evt);
            }
        });
        getContentPane().add(confirmarRecebi, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 400, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nome");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tipo do pagamento");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Data");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Valor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Recebimento");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Recebimento.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 820, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DataRecebiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataRecebiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataRecebiActionPerformed

    private void confirmarRecebiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarRecebiActionPerformed
        // nt id, String nome, float valor, String data, String tipDa
        Recebimento recebimento = new Recebimento();

        recebimento.setNome(NomeRecebi.getText().toString());
        recebimento.setValor(ValorRecebi.getText().toString());
        recebimento.setData(DataRecebi.getText().toString());
        recebimento.setTipo(TipoReceb.getSelectedItem().toString());

        recebimentoDAO.inserir(recebimento);

        JOptionPane.showMessageDialog(null, " Entrada lançada com sucesso !!");


    }//GEN-LAST:event_confirmarRecebiActionPerformed

    private void VoltarRecebiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarRecebiActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VoltarRecebiActionPerformed

    private void ValorRecebiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorRecebiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorRecebiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recebimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recebimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recebimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recebimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recebimentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField DataRecebi;
    private javax.swing.JTextField NomeRecebi;
    private javax.swing.JComboBox<String> TipoReceb;
    private javax.swing.JFormattedTextField ValorRecebi;
    private javax.swing.JButton VoltarRecebi;
    private javax.swing.JButton confirmarRecebi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
