/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JOptionPane;

/**
 *
 * @author ANNY FIORESE
 */
public class Relatorio extends javax.swing.JFrame {

    /**
     * Creates new form Relatorio
     */
    public Relatorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VoltarRelatorio = new javax.swing.JButton();
        GerarRelatorio = new javax.swing.JButton();
        TipoRelatorio = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Vizualizar = new javax.swing.JEditorPane();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VoltarRelatorio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        VoltarRelatorio.setBorder(null);
        VoltarRelatorio.setContentAreaFilled(false);
        VoltarRelatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VoltarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarRelatorioActionPerformed(evt);
            }
        });
        getContentPane().add(VoltarRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 40, 40));

        GerarRelatorio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        GerarRelatorio.setText("Gerar");
        GerarRelatorio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerarRelatorioActionPerformed(evt);
            }
        });
        getContentPane().add(GerarRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 50, 20));

        TipoRelatorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entradas", "Saidas", "Fieis", " " }));
        getContentPane().add(TipoRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 160, 20));

        jScrollPane1.setViewportView(Vizualizar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 370, 400));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gerar Relatorio");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Relatorio.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 820, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerarRelatorioActionPerformed
        // TODO add your handling code here:
        try {
            String opcao = TipoRelatorio.getSelectedItem().toString();
            if (opcao == "Saidas") {
                Path caminho = Paths.get("dispesas.csv");
                byte[] texto = Files.readAllBytes(caminho);
                String leitura = new String(texto);

                Vizualizar.setText(leitura);

            }
            if (opcao == "Entradas") {
                Path caminho = Paths.get("recebimento.csv");
                byte[] texto = Files.readAllBytes(caminho);
                String leitura = new String(texto);

                Vizualizar.setText(leitura);
            }
            
            if (opcao == "Fieis"){
                Path caminho = Paths.get("dizimista.csv");
                byte[] texto = Files.readAllBytes(caminho);
                String leitura = new String(texto);

                Vizualizar.setText(leitura);
                
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Desculpe, ocorreu um erro inesperado!");
        }
    }//GEN-LAST:event_GerarRelatorioActionPerformed

    private void VoltarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarRelatorioActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VoltarRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GerarRelatorio;
    private javax.swing.JComboBox<String> TipoRelatorio;
    private javax.swing.JEditorPane Vizualizar;
    private javax.swing.JButton VoltarRelatorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
